### ISSUE TITLE
Fail to compile on VS2019

### ISSUE THREAD

**Issue by JCKodel** [jamesmontemagno/InAppBillingPlugin#239]
## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: n/a
Simulator Tested On: n/a
Version of VS: 16.2.3
Version of Xamarin: Xamarin Forms 4.0.0.497661

### Steps to reproduce the Behavior
I have an old project that runs fine in VS 2017, but compiling it in VS 2019 gives me this error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to create JavaTypeInfo for class: Plugin.InAppBilling.InAppBillingImplementation/InAppBillingServiceConnection due to System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Projects\KD\MeuCronogramaCapilar.Stencil\MeuCronogramaCapilar.Xamarin\MeuCronogramaCapilar.Xamarin\MeuCronogramaCapilar.Xamarin.Android\obj\Release\90\android\src\md51ac510169250b1889517cb663f7eceaa\InAppBillingImplementation_InAppBillingServiceConnection.java'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Xamarin.Android.Tools.Files.CopyIfStreamChanged(Stream stream, String destination)
   at Xamarin.Android.Tasks.Generator.CreateJavaSources(TaskLoggingHelper log, IEnumerable`1 javaTypes, String outputPath, String applicationJavaClass, String androidSdkPlatform, Boolean useSharedRuntime, Boolean generateOnCreateOverrides, Boolean hasExportReference)	MeuCronogramaCapilar.Xamarin.Android			

```

**Comment by jamesmontemagno** [comment]
Looks like this is a file too long exception. Make sure you put it in a folder to c:\source
