### ISSUE TITLE
Linker issue: com.android.billingclient.api.ProxyBillingActivity cannot be instantiated

### ISSUE THREAD

**Issue by maxkoshevoi** [jamesmontemagno/InAppBillingPlugin#374]
App crashes when linking is set to `Sdk and User Assemblies`. Everything works fine with `Sdk Assemblies Only`

Full exception:
```
Unable to instantiate activity ComponentInfo{com.whitebox.nuretimetable/com.android.billingclient.api.ProxyBillingActivity}:
java.lang.InstantiationException: java.lang.Class<com.android.billingclient.api.ProxyBillingActivity> cannot be instantiated
```

<details><summary>Stack trace</summary>

```
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.whitebox.nuretimetable/com.android.billingclient.api.ProxyBillingActivity}: java.lang.InstantiationException: java.lang.Class<com.android.billingclient.api.ProxyBillingActivity> cannot be instantiated
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2744)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2921)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6662)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.InstantiationException: java.lang.Class<com.android.billingclient.api.ProxyBillingActivity> cannot be instantiated
	at java.lang.Class.newInstance(Native Method)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
	at androidx.test.runner.MonitoringInstrumentation.newActivity(MonitoringInstrumentation.java:10)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
```

</details>

## Bug Information

Version Number of Plugin: 4.0.2
Device Tested On: Google Pixel 4 XL
Simulator Tested On: Google Pixel 3, Xiaomi Redmi 6A
Version of VS: 16.9.4
Version of Xamarin: 5.0.0.2012
Versions of other things you are using:

### Steps to reproduce the Behavior
- Add this plugin to the project 
- Build app with following configuration:
<details>

![image](https://user-images.githubusercontent.com/6609929/115264366-e95a8500-a13e-11eb-8289-f06de71309ad.png)

</details>

- Try to buy something

### Expected Behavior
Plugin works as expected

### Actual Behavior
App crashes

**Comment by jamesmontemagno** [comment]
updated readme

**Comment by maxkoshevoi** [comment]
@jamesmontemagno Ow, sorry, missed those steps in readme. This assembly was already specified there.

Could you revert your changes?

![image](https://user-images.githubusercontent.com/6609929/115742261-2b7f0300-a399-11eb-8011-fe6796c861ce.png)

**Comment by jamesmontemagno** [comment]
teheheh :)
