### ISSUE TITLE
When will you support version of Xamarin.Android.Google.BillingClient 5.1.0 ?

### ISSUE THREAD

**Issue by pulmuone** [jamesmontemagno/InAppBillingPlugin#521]
When will you support version of Xamarin.Android.Google.BillingClient 5.1.0 ?

**Comment by jamesmontemagno** [comment]
Is thereA feature you need?

**Comment by pulmuone** [comment]
> Is there a feature you need?

I don't need it right now, but I'm wondering why the InAppBillingPlugin is giving me an error.
And Google will force Version someday.
Thank you.

**Comment by jamesmontemagno** [comment]
Gotcha, yeah you will want to use whatever I bundle with it. I will start to lock the versions better.

I will work on it this month most likely.

**Comment by pulmuone** [comment]
> Gotcha, yeah you will want to use whatever I bundle with it. I will start to lock the versions better.
> I will work on it this month most likely.

Thank you so much~^^.

**Comment by daniel-lamolony** [comment]
Another vote to support **Xamarin.Android.Google.BillingClient 5.1.0** for the May 2022 changes please.

In **CrossInAppBilling.Current.GetProductInfoAsync**, _QuerySkuDetailsAsync_ is deprecated in favour of _QueryProductDetailsAsync_ to get product details using the new model.

https://support.google.com/googleplay/android-developer/answer/12154973
https://support.google.com/googleplay/android-developer/answer/12124625

**Comment by jamesmontemagno** [comment]
I have started work on implementation. pretty large change to return values.

**Comment by daniel-lamolony** [comment]
Thank you, you’ve earned some more coffee coins for your efforts 😊

**Comment by Stefan171086** [comment]
Hey @jamesmontemagno,
I´m actually working on implementing your awesome plugin and dealing with in app billing on android.
Is there a time horizont when following pull request will be merged and available as NuGet package?
[https://github.com/jamesmontemagno/InAppBillingPlugin/pull/532](url)

Thanks and BR
Stefan

**Comment by petar-marinov** [comment]
Version above 5 of Google BillingClient is now mandatory on Google Play: 

![image](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/22096803/4b31d783-8303-4019-bb4e-b673edac0021)

**Comment by pulmuone** [comment]
Google Play Console :
Starting on August 2, 2023, all new apps must use Billing Library version 5 or newer. By November 1, 2023, all updates to existing apps must use Billing Library version 5 or newer.

**Comment by PonyOny** [comment]
Any info about this, when will you be able to release a new version with V5? for Xamarin & MAUI

**Comment by JeroenBer** [comment]
Now received this message in Google Play Store:

"We've detected that this app is using an old version of Google Play Billing. From 1 November 2023, all app updates must use Billing Library version 5 or newer."

**Comment by jamesmontemagno** [comment]
Yes, it must have bene an error on their side, still lots of time until their august/nov deadline.

**Comment by petar-marinov** [comment]
I’m already experiencing this error and cannot publish an update for one of
our apps.

**Comment by jamesmontemagno** [comment]
Will be pushing out v7 beta for folks to test this is built against billing api v6 which was just released

**Comment by daniel-lamolony** [comment]
AndroidExtras.SubscriptionOfferDetails is coming through as null on 7.0.0-beta

**Comment by pulmuone** [comment]
version  : Plugin.InAppBilling 7.0.0-beta 
var purchase = await billing.PurchaseAsync(productIdSub, ItemType.Subscription);
Error Message : 
Issue connecting: Java.Lang.NullPointerException: offerToken is required for constructing ProductDetailsParams.
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00068] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/JniEnvironment.g.cs:11524 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00036] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:867 
  at Android.BillingClient.Api.BillingFlowParams+ProductDetailsParams+Builder.Build () [0x00000] in C:\a\_work\1\s\generated\com.android.billingclient.billing\obj\Release\monoandroid12.0\generated\src\Android.BillingClient.Api.BillingFlowParams.cs:344 
  at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync (System.String productSku, System.String itemType, System.String obfuscatedAccountId, System.String obfuscatedProfileId) [0x00119] in D:\a\1\s\src\Plugin.InAppBilling\InAppBilling.android.cs:360 
  at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync (System.String productId, Plugin.InAppBilling.ItemType itemType, System.String obfuscatedAccountId, System.String obfuscatedProfileId) [0x00131] in D:\a\1\s\src\Plugin.InAppBilling\InAppBilling.android.cs:339 
  at BarcodeScanner.ViewModels.PaymentViewModel.PurchaseSubscription () [0x00314] in D:\01.SourcePrivate\BarcodeScanner2\BarcodeScanner\BarcodeScanner\ViewModels\PaymentViewModel.cs:273 
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: offerToken is required for constructing ProductDetailsParams.
	at com.google.android.gms.internal.play_billing.zzm.zzc(com.android.billingclient:billing@@6.0.0:1)
	at com.android.billingclient.api.BillingFlowParams$ProductDetailsParams$Builder.build(com.android.billingclient:billing@@6.0.0:2)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by pulmuone** [comment]
> AndroidExtras.SubscriptionOfferDetails is coming through as null on 7.0.0-beta

![image](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/42885949/abf9d52b-9b93-4435-b67d-b5792c61859c)

same issue.

**Comment by jamesmontemagno** [comment]
> Will that beta be compatible with Xamarin & MAUI?

Yes, of course, v6 is already.

**Comment by jamesmontemagno** [comment]
> AndroidExtras.SubscriptionOfferDetails is coming through as null on 7.0.0-beta

Please post issues on the PR as I am address it there: https://github.com/jamesmontemagno/InAppBillingPlugin/pull/532

**Comment by PonyOny** [comment]
> > Will that beta be compatible with Xamarin & MAUI?
> 
> Yes, of course, v6 is already.

I’m using 5.x as you mention on your doc to better use v5 for Xamarin & v6 for Maui, so upcoming v7 will be safe to use with Xamarin?

**Comment by jamesmontemagno** [comment]
> > > Will that beta be compatible with Xamarin & MAUI?
> > 
> > 
> > Yes, of course, v6 is already.
> 
> I’m using 5.x as you mention on your doc to better use v5 for Xamarin & v6 for Maui, so upcoming v7 will be safe to use with Xamarin?

Yup! I am merging everything together and all being built against latest bits in VS 2022 . So should be good there.

**Comment by pulmuone** [comment]
Version 7.0.5-beta works fine on Android/iOS. The customer's subscription is being paid.
Thank you.

**Comment by jamesmontemagno** [comment]
> Version 7.0.5-beta works fine on Android/iOS. The customer's subscription is being paid. Thank you.

Awesome!!! Thank you for confirming!!! I will do some more reviews and get feedback until end of month.

**Comment by ecosimini** [comment]
Hi James, I'm a huge fan! I watch all your videos :) the MAUI ones anyways.
Do you by any chance know if this billing client update is close to seeing stable nuget release?
