### ISSUE TITLE
Mono.Linker.MarkException : error

### ISSUE THREAD

**Issue by mohammadrezahamedi** [jamesmontemagno/InAppBillingPlugin#529]
I get this error when I want to build the project for release, but in the debug mode app can build.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task`1<System.Collections.Generic.IEnumerable`1<Plugin.InAppBilling.InAppBillingPurchase>> Plugin.InAppBilling.InAppBillingImplementation::GetPurchasesAsync(Plugin.InAppBilling.ItemType)' in assembly: 'Plugin.InAppBilling.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Android.BillingClient.Api.Purchase/PurchasesResult
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() 	

## Bug Information

Version Number of Plugin:
6.7

**Comment by jamesmontemagno** [comment]
make sure you have linker settings correct https://github.com/jamesmontemagno/InAppBillingPlugin/#version-4-linker-settings
