### ISSUE TITLE
Issues with 7.0.5 on Android (probably silly mistakes!)

### ISSUE THREAD

**Issue by aresem** [jamesmontemagno/InAppBillingPlugin#566]
I've moved over from old-school Xamarin (using Mono.Android) to .NET7, and updated the InAppBilling plugin to 7.0.5 but am hitting some problems.

**Note** I'm testing on a Release build on a physical device, but deployed from VS (not as an internal build from the Play Store). Also, on the old version of the Android app build in VS2019 and using v7.0.5 seems to work without any issue.

On the VS2022 build using a Android .NET application:

With R8 enabled, I get a runtime a Java ClassNotFound exception:

```
Java.Lang.ClassNotFoundException: com.android.billingclient.api.BillingClient
   at Java.Interop.JniEnvironment.Types.TryFindClass(String classname, Boolean throwOnError)
   at Java.Interop.JniEnvironment.Types.FindClass(String classname)
   at Java.Interop.JniType..ctor(String classname)
   at Java.Interop.JniType.GetCachedJniType(JniType& cachedType, String classname)
   at Java.Interop.JniPeerMembers.get_JniPeerType()
   at Java.Interop.JniPeerMembers.JniStaticMethods.GetMethodInfo(String method, String signature)
   at Java.Interop.JniPeerMembers.JniStaticMethods.GetMethodInfo(String encodedMember)
   at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeObjectMethod(String encodedMember, JniArgumentValue* parameters)
   at Android.BillingClient.Api.BillingClient.NewBuilder(Context context)
   at Plugin.InAppBilling.InAppBillingImplementation.ConnectAsync(Boolean enablePendingPurchases)
   at ...
```

If I disable R8, I get a FileNotFound exception when looking for Microsoft.Maui.Essentials which is *not* included in my project mainly because I can't figure out how to actually include it - there's a lot of runtime and ref nuget packages but no top-level nuget to add.

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Maui.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Microsoft.Maui.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync(String productSku, String itemType, String obfuscatedAccountId, String obfuscatedProfileId, String subOfferToken)
   at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync(String productId, ItemType itemType, String obfuscatedAccountId, String obfuscatedProfileId, String subOfferToken)
   at ...
```

Is there a simple solution to this? 

- Do I just need to add Maui.Essentials (in which case can someone explain how?)
- I've tried various proguard config files with R8 but can't get that missing class exception to disappear - is there a template proguard file for v7 of the InAppBilling library? The proguard file I've tried is this:

```
    -keep class com.google.android.play.core.common.PlayCoreDialogWrapperActivity
    -keep class com.google.android.play.core.review.** { *; }
    -keep class com.google.android.play.core.tasks.** { *; }

    -dontwarn com.google.android.gms.**
    -keep class com.google.android.gms.**

    -keep class android.support.v7.widget.FitWindowsLinearLayout { *; }
```

Thanks for any help!

**Comment by aresem** [comment]
```
-keep class com.android.billingclient.api.** { *; }
-keep class com.android.vending.billing.** { *; }
```
